language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

matrix:
  include:
    # Add build to run tests against Firefox inside Travis environment (other runs are against HtmlUnit by default)
    - php: 7.1
      env: BROWSER_NAME="firefox"
      addons:
        firefox: "45.8.0esr"
        apt:
          packages:
            - oracle-java8-installer

    # Build with lowest possible dependencies
    - php: 7.1
      env: dependencies="--prefer-lowest"

    # Saucelabs builds
    - php: 7.1
      env: SAUCELABS=1 BROWSER_NAME="firefox" VERSION="47.0" PLATFORM="Windows 10"
      before_script:
        - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
        - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"
      addons:
        sauce_connect: true
        jwt:
          secure: HPq5xFhosa1eSGnaRdJzeyEuaE0mhRlG1gf3G7+dKS0VniF30husSyrxZhbGCCKBGxmIySoAQzd43BCwL69EkUEVKDN87Cpid1Ce9KrSfU3cnN8XIb+4QINyy7x1a47RUAfaaOEx53TrW0ShalvjD+ZwDE8LrgagSox6KQ+nQLE=
    - php: 7.1
      env: SAUCELABS=1 BROWSER_NAME="chrome" VERSION="latest" PLATFORM="Windows 10"
      before_script:
        - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
        - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"
      addons:
        sauce_connect: true
        jwt:
          secure: HPq5xFhosa1eSGnaRdJzeyEuaE0mhRlG1gf3G7+dKS0VniF30husSyrxZhbGCCKBGxmIySoAQzd43BCwL69EkUEVKDN87Cpid1Ce9KrSfU3cnN8XIb+4QINyy7x1a47RUAfaaOEx53TrW0ShalvjD+ZwDE8LrgagSox6KQ+nQLE=

    # Codestyle check build
    - php: 7.1
      env: CHECK_CODESTYLE=1
      before_script: ~
      script: composer codestyle:check
      after_script: ~
      after_success: ~

env:
  global:
    - DISPLAY=:99.0

cache:
  directories:
    - $HOME/.composer/cache
    - jar

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction $dependencies

before_script:
  - sh -e /etc/init.d/xvfb start
  - if [ ! -f jar/selenium-server-standalone-3.1.0.jar ]; then wget -q -t 3 -P jar https://selenium-release.storage.googleapis.com/3.1/selenium-server-standalone-3.1.0.jar; fi
  - /usr/lib/jvm/java-8-oracle/bin/java -Dwebdriver.firefox.marionette=false -jar jar/selenium-server-standalone-3.1.0.jar -log ./logs/selenium.log &
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for Selenium server on port 4444...; done; echo "Selenium server started"
  - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
  - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"

script:
  - if [ -n "$SAUCELABS" ]; then EXTRA_PARAMS="--exclude-group exclude-saucelabs"; fi
  - ./vendor/bin/phpunit --coverage-clover ./logs/coverage-clover.xml $EXTRA_PARAMS

after_script:
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/php-server.log ]; then cat ./logs/php-server.log; fi

after_success:
  - travis_retry php vendor/bin/coveralls -v

addons:
  apt:
    packages:
      - oracle-java8-installer
